# Generated by Django 3.2 on 2021-04-07 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PortFolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='summarry',
            new_name='summary',
        ),
    ]
